[package]
name = "fizz_rs"
version = "0.1.0"
authors = ["Jay Shah <Jay9596@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = {version = "1.0", features = ["derive"] }